//
//  HomeCollectionViewData.swift
//  TravelApp
//
//  Created by Samet Korkmaz on 18.08.2024.
//

import Foundation

struct HomeCollectionViewData {
    
   static var collectionHotels: [HotelModel] = [
    
        HotelModel(data: [Datum(id: "a11", name: "Bosphorus Palace Hotel", hotelDescription: "Luxurious Outdoor Pool and Restaurant Indulge in a relaxing stay at Abuja Continental Hotel, where you can enjoy our refreshing outdoor pool and savor delicious meals at our on-site restaurant. Recreational Activities and Fitness Amenities Stay active during your visit with access to our tennis court and well-equipped fitness centre. Unwind after a long day in our nightclub or shared lounge. Convenient Facilities and Services Benefit from our meeting facilities, free parking, and comfortable accommodations featuring air conditioning, private bathrooms, and work desks. Book now for an unforgettable experience at Abuja Continental Hotel.", country: "TR", city: "İstanbul", address: "Ladi Kwali Street", mainPhoto: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/10/4f/f0/bosphorus-palace-hotel.jpg?w=700&h=-1&s=1", stars: 5.0)], hotelIDS: "1"),
        HotelModel(data: [Datum(id: "a22", name: "The Westin Copley Place", hotelDescription: "Luxurious Outdoor Pool and Restaurant Indulge in a relaxing stay at Abuja Continental Hotel, where you can enjoy our refreshing outdoor pool and savor delicious meals at our on-site restaurant. Recreational Activities and Fitness Amenities Stay active during your visit with access to our tennis court and well-equipped fitness centre. Unwind after a long day in our nightclub or shared lounge. Convenient Facilities and Services Benefit from our meeting facilities, free parking, and comfortable accommodations featuring air conditioning, private bathrooms, and work desks. Book now for an unforgettable experience at Abuja Continental Hotel.", country: "US ", city: "New York", address: "Ladi Kwali Street", mainPhoto: "https://media-api.xogrp.com/images/9f14737c-2be7-4b2f-80ed-d9c36556e7dd~rs_768.h", stars: 5.0)], hotelIDS: "2"),
        HotelModel(data: [Datum(id: "a33", name: "Renaissance Paris Nobel", hotelDescription: "Luxurious Outdoor Pool and Restaurant Indulge in a relaxing stay at Abuja Continental Hotel, where you can enjoy our refreshing outdoor pool and savor delicious meals at our on-site restaurant. Recreational Activities and Fitness Amenities Stay active during your visit with access to our tennis court and well-equipped fitness centre. Unwind after a long day in our nightclub or shared lounge. Convenient Facilities and Services Benefit from our meeting facilities, free parking, and comfortable accommodations featuring air conditioning, private bathrooms, and work desks. Book now for an unforgettable experience at Abuja Continental Hotel.", country: "FR", city: "Paris", address: "Ladi Kwali Street", mainPhoto: "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/900/450/75/dam/wdpro-assets/dlr/places-to-stay/disneyland-hotel/resort-overview/disneyland-hotel-06.jpg?1723533862220", stars: 5.0)], hotelIDS: "3"),
        HotelModel(data: [Datum(id: "a44", name: "Hotel Bristol Berlin", hotelDescription: "Luxurious Outdoor Pool and Restaurant Indulge in a relaxing stay at Abuja Continental Hotel, where you can enjoy our refreshing outdoor pool and savor delicious meals at our on-site restaurant. Recreational Activities and Fitness Amenities Stay active during your visit with access to our tennis court and well-equipped fitness centre. Unwind after a long day in our nightclub or shared lounge. Convenient Facilities and Services Benefit from our meeting facilities, free parking, and comfortable accommodations featuring air conditioning, private bathrooms, and work desks. Book now for an unforgettable experience at Abuja Continental Hotel.", country: "DE", city: "Berlin", address: "Ladi Kwali Street", mainPhoto: "https://pix10.agoda.net/hotelImages/124/1246280/1246280_16061017110043391702.jpg?ca=6&ce=1&s=414x232&ar=16x9", stars: 5.0)], hotelIDS: "4"),
        HotelModel(data: [Datum(id: "a55", name: "Bahiamar Hotel", hotelDescription: "Luxurious Outdoor Pool and Restaurant Indulge in a relaxing stay at Abuja Continental Hotel, where you can enjoy our refreshing outdoor pool and savor delicious meals at our on-site restaurant. Recreational Activities and Fitness Amenities Stay active during your visit with access to our tennis court and well-equipped fitness centre. Unwind after a long day in our nightclub or shared lounge. Convenient Facilities and Services Benefit from our meeting facilities, free parking, and comfortable accommodations featuring air conditioning, private bathrooms, and work desks. Book now for an unforgettable experience at Abuja Continental Hotel.", country: "BR", city: "Santos", address: "Ladi Kwali Street", mainPhoto: "https://www.luxuryabode.com/mona/img/hotels.jpg", stars: 5.0)], hotelIDS: "5"),
        HotelModel(data: [Datum(id: "a66", name: "Royal Garden Hotel", hotelDescription: "Luxurious Outdoor Pool and Restaurant Indulge in a relaxing stay at Abuja Continental Hotel, where you can enjoy our refreshing outdoor pool and savor delicious meals at our on-site restaurant. Recreational Activities and Fitness Amenities Stay active during your visit with access to our tennis court and well-equipped fitness centre. Unwind after a long day in our nightclub or shared lounge. Convenient Facilities and Services Benefit from our meeting facilities, free parking, and comfortable accommodations featuring air conditioning, private bathrooms, and work desks. Book now for an unforgettable experience at Abuja Continental Hotel.", country: "GB", city: "London", address: "Ladi Kwali Street", mainPhoto: "https://www.washingtonresorthotel.com/images/slider/55-1-Image16.jpg", stars: 5.0)], hotelIDS: "6"),
        HotelModel(data: [Datum(id: "a77", name: "Hotel Patria", hotelDescription: "Luxurious Outdoor Pool and Restaurant Indulge in a relaxing stay at Abuja Continental Hotel, where you can enjoy our refreshing outdoor pool and savor delicious meals at our on-site restaurant. Recreational Activities and Fitness Amenities Stay active during your visit with access to our tennis court and well-equipped fitness centre. Unwind after a long day in our nightclub or shared lounge. Convenient Facilities and Services Benefit from our meeting facilities, free parking, and comfortable accommodations featuring air conditioning, private bathrooms, and work desks. Book now for an unforgettable experience at Abuja Continental Hotel.", country: "IT", city: "Roma", address: "Ladi Kwali Street", mainPhoto: "https://cdn.sanity.io/images/ocl5w36p/production/11f832e11bcc7b99c7781ac0911a9e475bad3ef9-950x760.jpg?w=480&auto=format&dpr=2", stars: 5.0)], hotelIDS: "7"),
        HotelModel(data: [Datum(id: "a88", name: "Novotel Madrid City", hotelDescription: "Luxurious Outdoor Pool and Restaurant Indulge in a relaxing stay at Abuja Continental Hotel, where you can enjoy our refreshing outdoor pool and savor delicious meals at our on-site restaurant. Recreational Activities and Fitness Amenities Stay active during your visit with access to our tennis court and well-equipped fitness centre. Unwind after a long day in our nightclub or shared lounge. Convenient Facilities and Services Benefit from our meeting facilities, free parking, and comfortable accommodations featuring air conditioning, private bathrooms, and work desks. Book now for an unforgettable experience at Abuja Continental Hotel.", country: "ES", city: "Madrid", address: "Ladi Kwali Street", mainPhoto: "https://assets.milestoneinternet.com/cdn-cgi/image/f=auto/the-hollywood-roosevelt-hotel/thehollywoodroosevelt/home-hero-slider/tropicana-pool.jpg?width=1500&height=852", stars: 5.0)], hotelIDS: "8"),
        HotelModel(data: [Datum(id: "a99", name: "Empark Prime Hotel", hotelDescription: "Luxurious Outdoor Pool and Restaurant Indulge in a relaxing stay at Abuja Continental Hotel, where you can enjoy our refreshing outdoor pool and savor delicious meals at our on-site restaurant. Recreational Activities and Fitness Amenities Stay active during your visit with access to our tennis court and well-equipped fitness centre. Unwind after a long day in our nightclub or shared lounge. Convenient Facilities and Services Benefit from our meeting facilities, free parking, and comfortable accommodations featuring air conditioning, private bathrooms, and work desks. Book now for an unforgettable experience at Abuja Continental Hotel.", country: "CN", city: "Pekin", address: "Ladi Kwali Street", mainPhoto: "https://www.arabellahotel.com/uploads/gallery/hakkimizda/slider-16613b1a6e9205.webp", stars: 5.0)], hotelIDS: "9"),
        HotelModel(data: [Datum(id: "a100", name: "Hotel Metropol Moscow", hotelDescription: "Luxurious Outdoor Pool and Restaurant Indulge in a relaxing stay at Abuja Continental Hotel, where you can enjoy our refreshing outdoor pool and savor delicious meals at our on-site restaurant. Recreational Activities and Fitness Amenities Stay active during your visit with access to our tennis court and well-equipped fitness centre. Unwind after a long day in our nightclub or shared lounge. Convenient Facilities and Services Benefit from our meeting facilities, free parking, and comfortable accommodations featuring air conditioning, private bathrooms, and work desks. Book now for an unforgettable experience at Abuja Continental Hotel.", country: "RU", city: "Moscow", address: "Ladi Kwali Street", mainPhoto: "https://radissonhotels.iceportal.com/image/radisson-blu-hotel-istanbul-pera/exterior/16256-116526-f76947877_3xl.jpg", stars: 5.0)], hotelIDS: "10")
    
    ]
    
}
